### ISSUE TITLE
What is the advantage compared to mqtt-websocket and default mqtt?

### ISSUE THREAD

**Issue by nkSong** [inventit/mqtt-websocket-jdk16-android#1]
Hi,

I want to know that advantage of mqtt-websocket.

Normaly mqtt-websocket is used on browser.

But, it is not run on browser(but, I needed... Because my teamLeader demands using websocket)

Can I know that the advantage of using websocket on Android?

Thanks.

**Comment by RangerMauve** [comment]
If you use Websockets on Android and in the browser, then you don't have to worry about setting up a separate broker that works over TCP. As well, certain cloud hosting solutions like Heroku only really work well with balancing load when you use HTTP, so they usually won't work well with TCP-based connections.

**Comment by nkSong** [comment]
If I use my server, I do not need use websocket obstinately?

The server supports TCP and WebSocket, but I think no reason must for use websocket.

Anyway, thanks for reply.

**Comment by RangerMauve** [comment]
Yeah, if you aren't using browser based clients or load balancers that use HTTP, then just a TCP server/client should be fine. However, these days most things are geared towards the web and therefore HTTP, so websockets are a good option to consider.

**Comment by nkSong** [comment]
OK
Thanks, RangerMauve!

**Comment by dbaba** [comment]
@RangerMauve thank you for the following up
@nkSong MQTT over WebSocket is one of the options you can choose. MQTT itself doesn't care of its transport, TCP, UDP, WebSocket or others can be applied.

The motivation I created it is that I needed a single endpoint (host) with standard HTTP ports(80/443) providing both HTTP I/F and MQTT I/F. In that case, if I assigned 80/443 to MQTT, then HTTP I/F wasn't available. But I could it by using MQTT over WebSocket since WebSocket is compatible with HTTP on establishing a connection.

**Comment by nkSong** [comment]
Oh, great.

Now, I understand that motivation of this project.

Thanks, @dbaba !!!
